@startuml

card app [
    アプリケーション
    --
    node
]

database db [
    データベース
    --
    いまはMySql
]

card Nginx [
    プロキシサーバー
    --
    Nginx
    ここでhttpsに変換
]

actor ユーザー as user

Nginx -- app
user -- Nginx
db -- app

@enduml