@startuml

package User{

    interface IUser{
        +userRegister: IUserRegister
        +userEditor: IUserEditor
    }

    interface IUserRegister{
        +registe()
    }

    interface IUserEditor{
        +edit()
        +delete()
    }

    class UserRegister{
        +registe()
    }

    class UserEditor{
        +edit()
        +delete()
    }

    class User

    IUserEditor <|.. UserEditor
    IUserRegister <|.. UserRegister
    IUserRegister <.. IUser
    IUserEditor <.. IUser
    IUser <|.. User

}

@enduml