@startuml

package User{

    interface IUser{
        +userRegister: IUserRegister
        +userEditor: IUserEditor
        +registe(name: string,credentials: Credentials)
        +edit(message: string)
        +delete()
    }

    interface IUserRegister{
        +registe()
    }

    interface IUserEditor{
        +edit()
        +delete()
    }

    class UserRegister{
        +registe()
    }

    class UserEditor{
        +edit()
        +delete()
    }

    class UserFactory{
        +create(id: string): IUser
    }

    class User

    IUserEditor <|.. UserEditor
    IUserRegister <|.. UserRegister
    IUserRegister <.. IUser
    IUserEditor <.. IUser
    IUser <|.. User
    UserEditor <.. UserFactory: <<create>>

}

@enduml