@startuml
client -> MessageContoroller
MessageContoroller -> Message.get
Message.get -> Message.get:message.user.isAbleToAccess(message.room_id)
note right:isAbleToAccessで送信可能なroomか検証。未許可ならDomainException
Message.get -> IMessageRepository
IMessageRepository -> IMessageRepository:get(message_id)
IMessageRepository -> Message.get
Message.get -> Message.get: message.user.trimCredentials()で認証情報を取り除く
@enduml