@startuml
client -> UserContoroller
UserContoroller -> LoginManager: authenticate(user)
LoginManager -> IUserRepository: authenticate(user)
IUserRepository -> IUserRepository: authenticate(user)
IUserRepository -> LoginManager
LoginManager -> UserContoroller:認証に失敗した場合は401エラー
@enduml