@startuml
package Message[
    メッセージパッケージ
    --
    IMessage
    IMessageEditor
    IMessageRegister
    ...
]
package Room[
    ルームパッケージ
    --
    これからリファクタリング
]
package User[
    ユーザーパッケージ
    --
    IUser
    IUserEditor
    IUserRegister
    ...
]
package Apply[
    DM申請
    --
    要リファクタリング
]
package Polymorphic[
    ポリモーフィック関連テーブルの管理
]


Message <.. User
Room <.. User
Apply <.. User
Polymorphic <-- Message



@enduml